# -*- coding: utf-8 -*-
"""LightGBM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E2bbkoL-69slYhxkQrs3VEAGh0TGPM-X
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import dask.dataframe as dd
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from imblearn.under_sampling import TomekLinks
from imblearn.over_sampling import SMOTE
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, roc_auc_score
from sklearn.model_selection import GridSearchCV
from lightgbm import LGBMClassifier
from sklearn.utils import class_weight

df = pd.read_csv('/content/drive/MyDrive/merged_df.csv', low_memory = False, on_bad_lines = "skip")
df = df.dropna(subset=['isFraud'])
print(df)
columns_to_drop= ['dist2', 'R_emaildomain', 'D6', 'D7', 'D8', 'D9', 'D12', 'D13', 'D14', 'V138', 'V139', 'V140', 'V141', 'V142', 'V143', 'V144', 'V145', 'V146', 'V147', 'V148', 'V149', 'V150', 'V151', 'V152', 'V153', 'V154', 'V155', 'V156', 'V157', 'V158', 'V159', 'V160', 'V161', 'V162', 'V163', 'V164', 'V165', 'V166', 'V167', 'V168', 'V169', 'V170', 'V171', 'V172', 'V173', 'V174', 'V175', 'V176', 'V177', 'V178', 'V179', 'V180', 'V181', 'V182', 'V183', 'V184', 'V185', 'V186', 'V187', 'V188', 'V189', 'V190', 'V191', 'V192', 'V193', 'V194', 'V195', 'V196', 'V197', 'V198', 'V199', 'V200', 'V201', 'V202', 'V203', 'V204', 'V205', 'V206', 'V207', 'V208', 'V209', 'V210', 'V211', 'V212', 'V213', 'V214', 'V215', 'V216', 'V217', 'V218', 'V219', 'V220', 'V221', 'V222', 'V223', 'V224', 'V225', 'V226', 'V227', 'V228', 'V229', 'V230', 'V231', 'V232', 'V233', 'V234', 'V235', 'V236', 'V237', 'V238', 'V239', 'V240', 'V241', 'V242', 'V243', 'V244', 'V245', 'V246', 'V247', 'V248', 'V249', 'V250', 'V251', 'V252', 'V253', 'V254', 'V255', 'V256', 'V257', 'V258', 'V259', 'V260', 'V261', 'V262', 'V263', 'V264', 'V265', 'V266', 'V267', 'V268', 'V269', 'V270', 'V271', 'V272', 'V273', 'V274', 'V275', 'V276', 'V277', 'V278', 'V322', 'V323', 'V324', 'V325', 'V326', 'V327', 'V328', 'V329', 'V330', 'V331', 'V332', 'V333', 'V334', 'V335', 'V336', 'V337', 'V338', 'V339', 'id_01', 'id_02', 'id_03', 'id_04', 'id_05', 'id_06', 'id_07', 'id_08', 'id_09', 'id_10', 'id_11', 'id_12', 'id_13', 'id_14', 'id_15', 'id_16', 'id_17', 'id_18', 'id_19', 'id_20', 'id_21', 'id_22', 'id_23', 'id_24', 'id_25', 'id_26', 'id_27', 'id_28', 'id_29', 'id_30', 'id_31', 'id_32', 'id_33', 'id_34', 'id_35', 'id_36', 'id_37', 'id_38', 'DeviceType', 'DeviceInfo']

"""columns_to drop represents the columns that have 80% or more missing values."""

for column in df.columns:
  most_common_value = df[column].mode()[0]
  df[column] = df[column].fillna(most_common_value)

df.drop_duplicates(inplace = True)



y = df['isFraud']
df = df.drop('isFraud', axis=1)
df = df.drop(columns=['Num']+columns_to_drop)

# Selecting numerical and categorical data
num_df = df.select_dtypes(include=['int64', 'float64'])
cat_df = df.select_dtypes(include=['object', 'category'])

# Initialize a label encoder for each categorical column in cat_df
for column in cat_df.columns:
    le = LabelEncoder()
    cat_df[column] = le.fit_transform(cat_df[column])

# Concatenate the numerical data and the newly encoded categorical data
final_df = pd.concat([num_df.reset_index(drop=True), cat_df.reset_index(drop=True)], axis=1)

del df
scaler = StandardScaler()
X_scaled = scaler.fit_transform(final_df)
del final_df

import shap

import matplotlib.pyplot as plt


from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split




# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

# Train a Random Forest model
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

# Initialize the JS visualization code for SHAP
shap.initjs()

# Create a SHAP explainer for trees
explainer = shap.TreeExplainer(model)

# Calculate SHAP values
shap_values = explainer.shap_values(X_train)

# Plot the partial dependence plot for the first feature
shap.dependence_plot(0, shap_values[0], X_train, feature_names=[i for i in range(len(X_train))])

# prompt: using shap i want a # Tracer le diagramme de dépendance partielle pour la première caractéristique
# Import OneHotEncoder
from sklearn.preprocessing import OneHotEncoder

# Encode categorical data using OneHotEncoder
ohe = OneHotEncoder(sparse=False, handle_unknown='ignore')
cat_df = ohe.fit_transform(cat_df)

# Concatenate the numerical data and the encoded categorical data
final_df = pd.concat([num_df.reset_index(drop=True), pd.DataFrame(cat_df).reset_index(drop=True)], axis=1)
shap.dependence_plot(0, shap_values, X_train, feature_names=iris.feature_names)

pca = PCA(n_components=0.95)  # 95% de variance
X_pca = pca.fit_transform(X_scaled)

X = pd.DataFrame(X_pca, columns=[f'PC_{i}' for i in range(X_pca.shape[1])])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

tomek = TomekLinks()
X_tl, y_tl = tomek.fit_resample(X = X_train, y = y_train)

from google.colab import drive
drive.mount('/content/drive')

model_lgb = LGBMClassifier(n_estimators=400,
                          learning_rate=0.05,
                          num_leaves=31,
                          colsample_bytree=0.8,
                          subsample_freq=3,
                          subsample=0.8,
                          random_state=42)

model_lgb.fit(X_train, y_train)

y_pred_lgb = model_lgb.predict(X_test)
y_pred_lgb_proba = model_lgb.predict_proba(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_lgb))
print("Precision:", precision_score(y_test, y_pred_lgb))
print("Recall:", recall_score(y_test, y_pred_lgb))
print("F1 Score:", f1_score(y_test, y_pred_lgb))
print("ROC AUC Score:", roc_auc_score(y_test, y_pred_lgb_proba[:, 1]))

cm = confusion_matrix(y_test, y_pred_lgb)
print("Confusion Matrix:")
print(cm)

param_grid = {
    'learning_rate': [0.01, 0.05, 0.1],
    'num_leaves': [31, 63, 127],
    'colsample_bytree': [0.6, 0.7, 0.8],
    'subsample_freq': [1, 2, 3],
    'subsample': [0.6, 0.7, 0.8],
}

grid_search = GridSearchCV(model_lgb, param_grid, cv=5, n_jobs=-1, verbose=1)
grid_search.fit(X_train, y_train)

print("Best parameters:", grid_search.best_params_)

best_model = grid_search.best_estimator_

y_pred_best = best_model.predict(X_test)
y_pred_proba_best = best_model.predict_proba(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_best))
print("Precision:", precision_score(y_test, y_pred_best))
print("Recall:", recall_score(y_test, y_pred_best))
print("F1 Score:", f1_score(y_test, y_pred_best))
print("ROC AUC Score:", roc_auc_score(y_test, y_pred_proba_best[:, 1]))

cm = confusion_matrix(y_test, y_pred_best)
print("Confusion Matrix:")
print(cm)